image_folder: pose_diffusion/samples/apple
image_size: 224
ckpt: /data1/yingbo/co3d_model_Apr16.pth
seed: 0

camera_dataloader:
    transforms_json: "/home/mutian/Workspace/PoseDiffusion/pose_diffusion/transforms.json" 
    camera_batch_size: 20
    num_workers: 4
    pin_memory: True
    persistent_workers: True
    drop_last: True

GGS:
    enable: True
    start_step: 10
    learning_rate: 0.01
    iter_num: 100
    sampson_max: 10
    min_matches: 10
    alpha: 0.0001


MODEL:
    _target_: models.PoseDiffusionModel

    pose_encoding_type: absT_quaR_logFL

    IMAGE_FEATURE_EXTRACTOR: 
        _target_: models.MultiScaleImageFeatureExtractor
        freeze: False

    DENOISER: 
        _target_: models.Denoiser
        TRANSFORMER:
            _target_:               models.TransformerEncoderWrapper
            d_model:                512
            nhead:                  4
            dim_feedforward:        1024
            num_encoder_layers:     8
            dropout:                0.1
            batch_first:            True
            norm_first:             True


    DIFFUSER:
        _target_: models.GaussianDiffusion
        beta_schedule: custom
